### PR TITLE
fix: re-work output dom to remove whitespace when copying

### LINKED ISSUE #480: Copy/pasting lines from the console view adds extra whitespace
Fiddle version: 0.16.0
macOS 10.15.3

To repro:
1. Run any app
2. Select some lines in the console window and copy them
3. Paste them into another text field

Expected behavior:
Each line in the console window is pasted one after another as they're visible in the console window, without extra whitespace, eg.

```
Saved files to /var/folders/_7/jm5cr84j7jd4v7btf2d3bqwm0000gn/T/tmp-19301PgnXP2Cz02Iy
Electron v999.999.999 started.
[51298:0915/102615.051186:INFO:content_main_runner_impl.cc(993)] Chrome is running in full browser mode.
```

Actual behavior:
```
Saved files to /var/folders/_7/jm5cr84j7jd4v7btf2d3bqwm0000gn/T/tmp-19301PgnXP2Cz02Iy

Electron v999.999.999 started.

[51298:0915/102615.051186:INFO:content_main_runner_impl.cc(993)] Chrome is running in full browser mode.

```

### PR DESCRIPTION
**Pull request by issacgerges**
Fixes #480 

This PR moves the console from `<p>` elements per row, to `<span>`s wrapped in `<div>` to avoid additional newlines when copy pasting. I modeled this very loosely around the structure used by the chrome inspector console.

copy-paste

### CODE REVIEW

**Review by erickzhao — APPROVED** [review]
WFM, thanks @issacgerges!

File: src/renderer/components/output.tsx [hunk 1]
```diff
@@ -85,13 +85,15 @@ export class Output extends React.Component<CommandsProps> {
     const lines = entry.text.split(/\r?\n/);
     const style: React.CSSProperties = entry.isNotPre
       ? { whiteSpace: 'initial' }
-      : {};
+      : { whiteSpace: 'pre' };
```
Comment (erickzhao) [inline src/renderer/components/output.tsx:88]: @issacgerges One comment: what does this line do? I tried manually switching the `initial` and `pre` values and didn't actually get any changes on my end.

screencast 2020-11-06 14-07-11

Comment (issacgerges) [reply src/renderer/components/output.tsx:88]: heya @erickzhao, `white-space: pre` tells the browser that line-breaking and whitespace are already "correct" in the output. With normal whitespace rules, the browser will break lines to fill the (layout) box and collapse repeated whitespace (`<span>     Hello</span>` would become `Hello`). With this rule it will only break lines when there are explicit linebreaks in the output and will preserve all whitespace.

In your example reducing the viewport size should show the text wrapping and not wrapping depending on that setting. Really glad you mentioned this though, helped me realized there was some CSS I had missed and could cleanup in this PR. Will send an update in a sec

**Review by codebytere — APPROVED** [review]
THANK YOU 🚀

**Review by erickzhao — APPROVED** [review]
