### PR TITLE
fix: use the latest version of Forge v6 for Fiddle Forge actions

### LINKED ISSUE #186: failing while make installers for fiddle
Hi 
for my system the Make installer step is failing. Please find the debug log attached.
[npm-debug.log](https://github.com/electron/fiddle/files/3062463/npm-debug.log)

let me know if any further information is required.
- Soumalya

### PR DESCRIPTION
**Pull request by malept**
Fixes #186.

### CODE REVIEW

File: src/renderer/transforms/forge.ts [hunk 1]
```diff
@@ -15,11 +15,11 @@ export async function forgeTransform(files: Files): Promise<Files> {
...
-      parsed.devDependencies['@electron-forge/cli'] = '6.0.0-beta.22';
-      parsed.devDependencies['@electron-forge/maker-deb'] = '6.0.0-beta.22';
-      parsed.devDependencies['@electron-forge/maker-rpm'] = '6.0.0-beta.22';
-      parsed.devDependencies['@electron-forge/maker-squirrel'] = '6.0.0-beta.22';
-      parsed.devDependencies['@electron-forge/maker-zip'] = '6.0.0-beta.22';
+      parsed.devDependencies['@electron-forge/cli'] = '6.0.0-beta.34';
+      parsed.devDependencies['@electron-forge/maker-deb'] = '6.0.0-beta.34';
+      parsed.devDependencies['@electron-forge/maker-rpm'] = '6.0.0-beta.34';
+      parsed.devDependencies['@electron-forge/maker-squirrel'] = '6.0.0-beta.34';
+      parsed.devDependencies['@electron-forge/maker-zip'] = '6.0.0-beta.34';
```
Comment (malept) [inline src/renderer/transforms/forge.ts]: This is the fast fix. Better fixes:

* caret the version
* Grab the Forge version from Fiddle's `package.json` file

**Comment by malept** [comment]
It's not clear to me why the Mac `make` step is failing on the contributors...
