### PR TITLE
fix: use process.env when running fiddle

### LINKED ISSUE #1470: Fiddle fails to launch Electron process on Linux
Fiddle 0.34.2 fails to launch Electron process on Linux. I've tested it on both Fedora (RPM package) and Ubuntu 22.04 (Debian package).

Fiddle's console output and the symbolicated crash are attached.

[console_output.txt](https://github.com/electron/fiddle/files/12745099/console_output.txt)
[symbolicated_crash.txt](https://github.com/electron/fiddle/files/12745100/symbolicated_crash.txt)

### PR DESCRIPTION
**Pull request by dsanders11**
Fixes #1470.

### CODE REVIEW

File: src/renderer/runner.ts [hunk 1]
```diff
@@ -333,7 +333,7 @@ export class Runner {
   private buildChildEnvVars(): { [x: string]: string | undefined } {
     const { isEnablingElectronLogging, environmentVariables } = this.appState;
 
-    const env = { ...process.env };
+    const env: Record<string, string> = {};
```
Comment (erikian) [inline src/renderer/runner.ts:336]: The `else` block on lines 342-345 can be removed, there's nothing to `delete` anymore

**Review by erikian — APPROVED** [review]

File: src/renderer/runner.ts (hunk 1 above)
Comment (dsanders11) [reply src/renderer/runner.ts:336]: Good catch, didn't notice those lines. That logic should actually probably be shifted to the main process so that the behavior matches what it was before the refactoring. Otherwise if those variables are in the environment in general, there will be a behavior change from before the main process refactor.

I'll look at refactoring this PR.

**Comment by dsanders11** [comment]
Updated this to better match the original behavior and added test coverage.

**Review by erikian — APPROVED** [review]
Minor nit, otherwise LGTM!

File: tests/main/fiddle-core-spec.ts [hunk 2]
```diff
@@ -0,0 +1,130 @@
...
+
+  return {
+    Installer: InstallerMock,
+    Runner: FiddleRunnerMock,
+  };
+});
+
+describe('fiddle-core', () => {
+  let runner: FiddleRunnerMock;
+  let env: NodeJS.ProcessEnv;
```
Comment (erikian) [inline tests/main/fiddle-core-spec.ts:25]: Can we make this somthing like `originalEnv`? There's a bunch of other `env`s elsewhere, this should make it slightly easier to tell them apart when skimming over the code
