### PR TITLE
fix: Create initial backup for preload editor

### LINKED ISSUE #284: Preload.js is not loaded nor uploaded
Hi there, 

**What works**
- preload.js is saved when you save or "save as forge" the project
- preload.js is loaded when you downloaded the gist

**What didn't works**
- preload.js is not loaded when you open existing project
- preload.js is not uploaded if you publish to gist

I haven't tried to package or make installer

thank you...

### PR DESCRIPTION
**Pull request by felixrieseberg**
When loading a Fiddle that contains a `preload` file, we didn't correctly load that content unless the user has previously opened the preload editor. The underlying cause was that we didn't create an initial text model for that editor, so we didn't have a place to store that value.

Closes #284

### CODE REVIEW

File: src/renderer/components/editor.tsx [hunk 1]
```diff
@@ -98,34 +98,53 @@ export class Editor extends React.Component<EditorProps> {
...
    */
   private async setContent() {
-    const { appState, id, monaco } = this.props;
+    const { appState, id } = this.props;
     const { version } = appState;
 
     const backup = appState.getAndRemoveEditorValueBackup(id);
 
-    if (backup && backup.model) {
+    console.log(id);
```
Comment (malept) [inline src/renderer/components/editor.tsx]: Stray debug line?
