### PR TITLE
fix: disable right click contextMenu in settings page

### LINKED ISSUE #1070: `ContextMenu` should be disabled in Settings page
Noticed a minor issue of the Right click `ContextMenu` which is can be seen in `Preference`/`Settings` page as well.

Screenshot 2022-05-10 at 10 04 39 PM

### PR DESCRIPTION
**Pull request by aryanshridhar**
Minor commit to fix #1070.
Edit: Not sure on how to mock the `contextMenu` behavior.

### CODE REVIEW

File: tests/renderer/components/settings-spec.tsx [hunk 1]
```diff
@@ -118,15 +118,15 @@ describe('Settings component', () => {
...
     // Toggle the setting again as if it was closed
     instance.toggleHasPopoverOpen();
 
     // trigger mock 'keyup' event
     map.keyup({ code: 'Escape' });
-    expect(Object.keys(map)).toHaveLength(1);
+    expect(Object.keys(map)).toHaveLength(2); // {'keyup','contextmenu'}
     expect(store.isSettingsShowing).toBe(false);
 
     // check if event listener is removed upon unmount
```
Comment (dsanders11) [inline tests/renderer/components/settings-spec.tsx:132]: Let's update this comment to be "// check if event listeners are removed upon unmount" now that there's multiple.

File: tests/renderer/components/settings-spec.tsx [hunk 2]
```diff
@@ -118,15 +118,15 @@ describe('Settings component', () => {
...
     expect(store.isSettingsShowing).toBe(true);
 
     // Toggle the setting again as if it was closed
     instance.toggleHasPopoverOpen();
 
     // trigger mock 'keyup' event
     map.keyup({ code: 'Escape' });
-    expect(Object.keys(map)).toHaveLength(1);
+    expect(Object.keys(map)).toHaveLength(2); // {'keyup','contextmenu'}
     expect(store.isSettingsShowing).toBe(false);
```
Comment (dsanders11) [inline tests/renderer/components/settings-spec.tsx:131]:
```suggestion

    // trigger mock 'contextmenu' event
    const preventDefault = jest.fn();
    map.contextmenu({ preventDefault });
    expect(Object.keys(map)).toHaveLength(2); // {'keyup','contextmenu'}
    expect(preventDefault).toHaveBeenCalled();

```

I haven't tested it, but you could try that to get a bit of test coverage. 🙂

**Review by dsanders11 — CHANGES_REQUESTED** [review]
Overall LGTM, couple minor comments. I think there's a lot more issues with the contextmenu throughout Fiddle (it's in a lot of places that probably don't make sense) but this is a step in the right direction.

**Review by BlackHole1 — APPROVED** [review]
LGTM

**Review by dsanders11 — APPROVED** [review]
